package com.example.demo.model;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.id
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.parent_id
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.type
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.comment
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.commentator
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    private Long commentator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.like_count
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    private Long likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.gmt_create
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.gmt_modified
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.id
     *
     * @return the value of COMMENT.id
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.id
     *
     * @param id the value for COMMENT.id
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.parent_id
     *
     * @return the value of COMMENT.parent_id
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.parent_id
     *
     * @param parentId the value for COMMENT.parent_id
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.type
     *
     * @return the value of COMMENT.type
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.type
     *
     * @param type the value for COMMENT.type
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.comment
     *
     * @return the value of COMMENT.comment
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.comment
     *
     * @param comment the value for COMMENT.comment
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.commentator
     *
     * @return the value of COMMENT.commentator
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    public Long getCommentator() {
        return commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.commentator
     *
     * @param commentator the value for COMMENT.commentator
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    public void setCommentator(Long commentator) {
        this.commentator = commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.like_count
     *
     * @return the value of COMMENT.like_count
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.like_count
     *
     * @param likeCount the value for COMMENT.like_count
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.gmt_create
     *
     * @return the value of COMMENT.gmt_create
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.gmt_create
     *
     * @param gmtCreate the value for COMMENT.gmt_create
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.gmt_modified
     *
     * @return the value of COMMENT.gmt_modified
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.gmt_modified
     *
     * @param gmtModified the value for COMMENT.gmt_modified
     *
     * @mbg.generated Sun Sep 01 17:46:12 CST 2019
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}